# This is a basic workflow to help you get started with Actions

name: Build Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7 \
          --output "type=image,push=false" \
          --tag "imZack/openresty:latest" \
          --file ./alpine/Dockerfile .

    - name: Docker Check Manifest
      run: |
        docker run --rm mplatform/mquery imZack/openresty:latest

    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        # The name of the image you would like to push
        name: imZack/openresty:latest
        # The login username for the registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # The login password for the registry
        password: ${{ secrets.DOCKER_PASSWORD }}
